name: Deploy
run-name: ${{ gitea.actor }} is deploying ${{ gitea.repository }}
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: host
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.157.0'
          extended: true

      - name: Build site
        run: |
          hugo build --gc --minify --baseURL https://qoheleth.post-self.ink --destination /opt/hugo/qoheleth.post-self.ink
